### ISSUE TITLE
Error: Couldn't locate plugins "include-code-editor"

### ISSUE THREAD

**Issue by kaihaase** [zingchart/gitbook-plugin-code-editor#1]
After I have integrated the plugin into the configuration file and running
`npm install gitbook-plugin-code-editor`, the following error message appears while generating the preview with `gitbook serve`: 

> Error: Couldn't locate plugins "include-code-editor", Run 'gitbook install' to install plugins from registry.

`gitbook install` ends with the following error message:

> Error: Registry returned 404 for GET on https://registry.npmjs.org/gitbook-plugin-include-code-editor

**Comment by christie-sorenson** [comment]
Thanks for the feedback.  

It should be: `"plugins": [ "code-editor"]` in the book.json file.

I've updated the README
