### ISSUE TITLE
GitBook Community in Google+

### ISSUE THREAD

**Issue by aleen42** [zingchart/gitbook-plugin-code-editor#3]
Hi zingchart,

I am Aleen (https://github.com/aleen42) , and the founder of GitBook Community in Google+: https://plus.google.com/communities/110696788983472771007, which aims to sharing books or plugins of GitBook, talking anything about it as well. Here I am sincerely inviting you to join us.  :punch:

**Comment by christie-sorenson** [comment]
Thanks Aleen.  We have joined the group.

**Comment by aleen42** [comment]
@christie-sorenson Welcome.
